spring.application.name=Ticket-Booking

# TiDB Cloud Serverless MySQL Connection Settings
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/ticket_booking_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3&useSSL=true&createDatabaseIfNotExist=true
spring.datasource.username=4ReUz4rExeG1jWC.root
spring.datasource.password=SaUayAG3otWPOSTv
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect